const SET_HTML = "SET_HTML"
const MINIMIZE_EDITOR = "MINIMIZE_EDITOR"
const MAXIMIZE_EDITOR = "MAXIMIZE_EDITOR"
const MINIMIZE_PREVIEWER = "MINIMIZE_PREVIEWER"
const MAXIMIZE_PREVIEWER = "MAXIMIZE_PREVIEWER"

export{
  SET_HTML,
  MINIMIZE_EDITOR,
  MAXIMIZE_EDITOR,
  MINIMIZE_PREVIEWER,
  MAXIMIZE_PREVIEWER
}